### ISSUE TITLE
Problem with GPU

### ISSUE THREAD

**Issue by imerelli** [rpmccordlab/SMILE#2]
Hi, I'm trying your software, but I get this error. I don't have a gpu and no nvidia driver are installed.
I'm using conda and I installed all the required packages. Can you help me in solving this issue?

>>> PairedSMILE_trainer(X_a = rna_X, X_b = dna_X, model = net, num_epoch=20)##training for 20 epochs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imerelli/scvar/SMILE.py", line 124, in PairedSMILE_trainer
    f_con = ContrastiveLoss(batch_size = batch_size,temperature = f_temp)
  File "/home/imerelli/scvar/contrastive_loss_pytorch.py", line 8, in __init__
    self.register_buffer("temperature", torch.tensor(temperature).cuda())
  File "/DATA_NFS/anaconda3/envs/integration/lib/python3.8/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/DATA_NFS/anaconda3/envs/integration/lib/python3.8/site-packages/torch/cuda/__init__.py", line 98, in _check_driver
    raise AssertionError("""
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by imerelli** [comment]
Hi,

getting a little bit in the code, I think the first problem is here:

         device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

because it calls the nvidia driver that I don't have.

But also correcting this in a very trivial way
   
         device = torch.device("cpu")#"cuda" if torch.cuda.is_available() else "cpu")

still in the have problems here:

        self.register_buffer("temperature", torch.tensor(temperature).cuda())
        self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, dtype=bool)).float().cuda())

**Comment by rpmccordlab** [comment]
If you modified the code of "contrastive_loss_pytorch" as below
self.register_buffer("temperature", torch.tensor(temperature))
self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, dtype=bool)).float()) 

and see if it would work for you.

The problem I see is from tensors are not on the same device (either GPU or CPU). loss calculation in "contrastive_loss_pytorch.py" is run on GPU by default. However, you set model on CPU for training. Make sure all tensors are calculated on the same device.

**Comment by imerelli** [comment]
I modified the code as you suggested, but it doesn't work. Here the error:

contrastive_loss_pytorch.py in __init__(self, batch_size, temperature)
      7         self.batch_size = batch_size
      8         self.register_buffer("temperature", torch.tensor(temperature))
----> 9         self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, dtype=bool)).float())
     10 
     11     def forward(self, emb_i, emb_j):

TypeError: eye() received an invalid combination of arguments - got (int, int, dtype=type), but expected one of:
 * (int n, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by rpmccordlab** [comment]
import torch
import torch.nn.functional as F

class ContrastiveLoss(torch.nn.Module):

    def __init__(self, batch_size, temperature=0.5):
        super().__init__()
        self.batch_size = batch_size
        self.register_buffer("temperature", torch.tensor(temperature))
        self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, 
                                                           dtype=bool)).float())
            
    def forward(self, emb_i, emb_j):
        """
        emb_i and emb_j are batches of embeddings, where corresponding indices are pairs
        z_i, z_j as per SimCLR paper
        """
        #z_i = F.normalize(emb_i, dim=1)
        #z_j = F.normalize(emb_j, dim=1)
        
        z_i = F.normalize(emb_i, dim=1,p=2)
        z_j = F.normalize(emb_j, dim=1,p=2)

        representations = torch.cat([z_i, z_j], dim=0)
        similarity_matrix = F.cosine_similarity(representations.unsqueeze(1), representations.unsqueeze(0), dim=2)
        
        sim_ij = torch.diag(similarity_matrix, self.batch_size)
        sim_ji = torch.diag(similarity_matrix, -self.batch_size)
        positives = torch.cat([sim_ij, sim_ji], dim=0)
        
        nominator = torch.exp(positives / self.temperature)
        denominator = self.negatives_mask * torch.exp(similarity_matrix / self.temperature)
    
        loss_partial = -torch.log(nominator / torch.sum(denominator, dim=1))
        loss = torch.sum(loss_partial) / (2 * self.batch_size)
        return loss



The code above did work and didn't report error. I am suspious that there might be some typos when you modified code.

**Comment by imerelli** [comment]
$ cat contrastive_loss_pytorch.py 
import torch
import torch.nn.functional as F

class ContrastiveLoss(torch.nn.Module):
    def __init__(self, batch_size, temperature=0.5):
        super().__init__()
        self.batch_size = batch_size
        self.register_buffer("temperature", torch.tensor(temperature))
        self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, dtype=bool)).float())
            
    def forward(self, emb_i, emb_j):
        """
        emb_i and emb_j are batches of embeddings, where corresponding indices are pairs
        z_i, z_j as per SimCLR paper
        """
        #z_i = F.normalize(emb_i, dim=1)
        #z_j = F.normalize(emb_j, dim=1)
        
        z_i = F.normalize(emb_i, dim=1,p=2)
        z_j = F.normalize(emb_j, dim=1,p=2)

        representations = torch.cat([z_i, z_j], dim=0)
        similarity_matrix = F.cosine_similarity(representations.unsqueeze(1), representations.unsqueeze(0), dim=2)
        
        sim_ij = torch.diag(similarity_matrix, self.batch_size)
        sim_ji = torch.diag(similarity_matrix, -self.batch_size)
        positives = torch.cat([sim_ij, sim_ji], dim=0)
        
        nominator = torch.exp(positives / self.temperature)
        denominator = self.negatives_mask * torch.exp(similarity_matrix / self.temperature)
    
        loss_partial = -torch.log(nominator / torch.sum(denominator, dim=1))
        loss = torch.sum(loss_partial) / (2 * self.batch_size)
        return loss

**Comment by imerelli** [comment]
Sorry, but I checked twice and there are no errors in the (very simple) correction I performed.
I uploaded the directory in which I'm working, if you could check what is wrong on a machine 
without cuda/GPU I would appreciate (i.e conda install pytorch torchvision cpuonly -c pytorch)
[scvar.zip](https://github.com/rpmccordlab/SMILE/files/8147243/scvar.zip)

**Comment by rpmccordlab** [comment]
We are sorry. It didn't work for you.

We checked many times. If you make 2 changes as below:

1. change
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
to
    device = torch.device("cpu")
in SMILE.py

2. change
    self.register_buffer("temperature", torch.tensor(temperature).cuda())
    self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, 
                                                       dtype=bool)).float().cuda())
to
    self.register_buffer("temperature", torch.tensor(temperature))
    self.register_buffer("negatives_mask", (~torch.eye(batch_size * 2, batch_size * 2, 
                                                       dtype=bool)).float())
in contrastive_loss_pytorch.py

We tried these changes on laptops that have no GPU and they would make code work.
