### ISSUE TITLE
single point for each cell in the UMAP

### ISSUE THREAD

**Issue by imerelli** [rpmccordlab/SMILE#3]
Hi, I'm using SMILE for integrating different single-cell omics and I find it very useful. One thing that biologists are asking me is to have in the UMAP a single point representing for each cell the all the different omics together. Do you think this make sense? In case, do you have any suggestion about have to proceed?

**Comment by rpmccordlab** [comment]
The idea we have to let a single point represent all different omics together is, for example, taking the mean of RNA embedding and ATAC embedding. 

If your data is joint-profiled, each cell will have a RNA embedding and ATAC embedding. So, you can average its embedding learned by SMILE, and visualize the whole joint-profiled data in UMAP, in which each dot compresses information from RNA and ATAC.

If your data is not joint-profiled, then you may infer ATAC information for a RNA cell through kNN or infer RNA information for a ATAC cell. After SMILE integration, you should be able to find k ATAC neighbors for a RNA cell, and vice verse. Then, you have each RNA cell with inferred ATAC information and visualize your data with UMAP.

We hope this idea would help.
